workflows:
  build_ios:
    name: Build iOS app (Next.js + Capacitor)
    environment:
      node: 20
      xcode: 15.3
      vars:
        APP_NAME: "RideNow"
        NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: $GOOGLE_MAPS_API_KEY

    scripts:
      # 1️⃣ Install dependencies
      - name: Install dependencies
        script: |
          npm install -g pnpm @capacitor/cli
          pnpm install

      # 2️⃣ Build Next.js app
      - name: Build Next.js
        script: |
          pnpm run build

      # 3️⃣ Add iOS platform (if not exists)
      - name: Add iOS platform
        script: |
          npx cap add ios || echo "iOS already exists"

      # 4️⃣ Sync Capacitor for iOS
      - name: Sync Capacitor
        script: |
          npx cap sync ios

      # 5️⃣ Install iOS Pods
      - name: Install iOS Pods
        script: |
          cd ios/App
          pod install --repo-update
          cd ../..

      # 6️⃣ Build iOS app for simulator
      - name: Build iOS app for simulator
        script: |
          cd ios/App
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -sdk iphonesimulator \
            -configuration Debug \
            -derivedDataPath ../../derived_data \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
          cd ../..

    artifacts:
      - derived_data/Build/Products/Debug-iphonesimulator/*.app


  # build_android:
  #   name: Build Android app (Next.js + Capacitor)
  #   environment:
  #     node: 20
  #     java: 21
  #     vars:
  #       APP_NAME: "RideNow"
  #       NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: $GOOGLE_MAPS_API_KEY

  #   scripts:
  #     # 1️⃣ Install dependencies
  #     - name: Install dependencies
  #       script: |
  #         npm install -g pnpm @capacitor/cli
  #         pnpm install

  #     # 2️⃣ Build Next.js app
  #     - name: Build Next.js for production
  #       script: |
  #         pnpm run build

  #     # 3️⃣ Add Android platform (if not exists)
  #     - name: Add Android platform
  #       script: |
  #         npx cap add android || echo "Android platform already exists"

  #     # 4️⃣ Sync Capacitor for Android
  #     - name: Sync Capacitor
  #       script: |
  #         npx cap sync android

  #     # 5️⃣ Build Android APK
  #     - name: Build Android APK
  #       script: |
  #         cd android
  #         ./gradlew assembleDebug
  #         cd ..

  #   artifacts:
  #     - android/app/build/outputs/apk/debug/*.apk
